<template>
  <div>
    <b-form-select
      v-model="selected"
      :options="symbols"
      @change="getData(selected)"
    ></b-form-select>
    <div class="FCo-table">
      <b-table striped :items="items" thead-class="hidden-header"></b-table>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      items: [['Loading...', 'Loading...']],
      selected: 'AAPL',
      symbols: [
        'AAPL',
        'ADBE',
        'ADI',
        'ADP',
        'ADSK',
        'AEP',
        'ALGN',
        'ALXN',
        'AMAT',
        'AMD',
        'AMGN',
        'AMZN',
        'ANSS',
        'ASML',
        'ATVI',
        'AVGO',
        'AXP',
        'BA',
        'BIDU',
        'BIIB',
        'BKNG',
        'CAT',
        'CDNS',
        'CDW',
        'CERN',
        'CHKP',
        'CHTR',
        'CMCSA',
        'COST',
        'CPRT',
        'CRM',
        'CSCO',
        'CSX',
        'CTAS',
        'CTSH',
        'CVX',
        'DIS',
        'DLTR',
        'DOCU',
        'DOW',
        'DXCM',
        'EA',
        'EBAY',
        'EXC',
        'FAST',
        'FB',
        'FISV',
        'FOX',
        'FOXA',
        'GILD',
        'GOOG',
        'GOOGL',
        'GS',
        'HD',
        'HON',
        'IBM',
        'IDXX',
        'ILMN',
        'INCY',
        'INTC',
        'INTU',
        'ISRG',
        'JD',
        'JNJ',
        'JPM',
        'KHC',
        'KLAC',
        'KO',
        'LRCX',
        'LULU',
        'MAR',
        'MCD',
        'MCHP',
        'MDLZ',
        'MELI',
        'MMM',
        'MNST',
        'MRK',
        'MRNA',
        'MRVL',
        'MSFT',
        'MTCH',
        'MU',
        'MXIM',
        'NFLX',
        'NKE',
        'NTES',
        'NVDA',
        'NXPI',
        'OKTA',
        'ORLY',
        'PAYX',
        'PCAR',
        'PDD',
        'PEP',
        'PG',
        'PTON',
        'PYPL',
        'QCOM',
        'REGN',
        'ROST',
        'SBUX',
        'SGEN',
        'SIRI',
        'SNPS',
        'SPLK',
        'SWKS',
        'TCOM',
        'TEAM',
        'TMUS',
        'TRV',
        'TSLA',
        'TXN',
        'UNH',
        'V',
        'VRSK',
        'VRSN',
        'VRTX',
        'VZ',
        'WBA',
        'WDAY',
        'WDC',
        'WMT',
        'XEL',
        'XLNX',
        'ZM',
      ],
    }
  },
  async mounted() {
    await this.getData('AAPL')
  },
  methods: {
    async getData(symbol) {
      await this.$axios
        .$get(`profile/${symbol}?apikey=28538229427f33fe650c547a9a1e99e7`)
        .then((res) => {
          this.items = [
            ['Currency', res[0].currency],
            ['Price', res[0].price],
            ['Beta', res[0].beta],
            ['Vol Avg', res[0].volAvg],
            ['market Cap', res[0].mktCap],
            ['Last Div', res[0].lastDiv],
            ['Range', res[0].range],
            ['Changes', res[0].changes],
            ['DFC Difference', res[0].dcfDiff],
            ['DFC', res[0].dcf],
            ['Exchange', res[0].exchangeShortName],
          ]
        })
    },
  },
}
</script>
